"""
DataMind AI — app.py  (FIXED & COMPLETE)

Root cause of download bug fixed:
  st.download_button MUST be rendered at top-level every run,
  with pre-generated bytes stored in st.session_state.
  Generating files inside `if form_submitted:` means the
  download buttons disappear on the very next rerun (when user clicks them).

Fix: generate bytes on form submit → store in session_state →
     render download buttons unconditionally every run if bytes exist.
"""

import streamlit as st
import pandas as pd
import numpy as np
import os, sys, io, json, tempfile, html
from datetime import datetime

sys.path.insert(0, os.path.dirname(__file__))

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="DataMind AI", page_icon="🧠",
    layout="wide", initial_sidebar_state="expanded",
)

# ── CSS ──────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
[data-testid="stAppViewContainer"]{background:#0f0f17;}
[data-testid="stSidebar"]{background:#15151f;border-right:1px solid #2a2a3a;}
.hero{background:#13131d;border:1px solid #2a2a3a;border-radius:16px;padding:36px 40px;margin-bottom:24px;}
.hero h1{font-size:2.2rem;font-weight:800;color:#e8e6ff;margin:0;}
.hero p{color:#9d9db8;font-size:1rem;margin-top:6px;}
.kpi-card{background:#13131d;border:1px solid #6d5fcc;border-radius:12px;padding:20px 18px;margin-bottom:10px;}
.kpi-val{font-size:2rem;font-weight:800;color:#a78bfa;}
.kpi-lbl{font-size:0.72rem;color:#6b6b8a;text-transform:uppercase;letter-spacing:0.08em;}
.kpi-story{font-size:0.88rem;color:#c5c3e0;margin-top:10px;line-height:1.6;}
.kpi-trend-up{color:#34d399;font-weight:700;}
.kpi-trend-down{color:#f87171;font-weight:700;}
.kpi-trend-flat{color:#9d9db8;font-weight:700;}
.agent-card{background:#13131d;border:1px solid #2a2a3a;border-radius:12px;padding:14px 18px;margin-bottom:10px;animation:fadeIn 0.4s ease;}
.agent-name{font-size:0.8rem;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:4px;}
.agent-msg{font-size:0.9rem;color:#c5c3e0;}
.debate-bubble{border-radius:12px;padding:12px 16px;margin:6px 0;font-size:0.9rem;}
.debate-left{background:#1e1e2e;border-left:3px solid #6d5fcc;color:#c5c3e0;}
.debate-right{background:#1a2030;border-left:3px solid #3b82f6;color:#c5c3e0;}
.metric-box{background:#13131d;border:1px solid #2a2a3a;border-radius:10px;padding:16px 20px;text-align:center;}
.metric-val{font-size:1.8rem;font-weight:700;color:#a78bfa;}
.metric-lbl{font-size:0.75rem;color:#6b6b8a;text-transform:uppercase;letter-spacing:0.05em;margin-top:2px;}
.risk-high{border-left:3px solid #ef4444;padding:10px 14px;background:#1f1215;border-radius:6px;margin:6px 0;font-size:0.85rem;color:#fca5a5;}
.risk-medium{border-left:3px solid #f59e0b;padding:10px 14px;background:#1f1a10;border-radius:6px;margin:6px 0;font-size:0.85rem;color:#fcd34d;}
.insight-card{background:#131a25;border:1px solid #1e3a5f;border-radius:8px;padding:12px 16px;margin:6px 0;font-size:0.85rem;color:#93c5fd;}
.share-box{background:#1a1a2e;border:2px solid #6d5fcc;border-radius:12px;padding:20px 24px;margin:16px 0;}
.thankyou-box{background:linear-gradient(135deg,#1a1a35 0%,#13131d 100%);border:2px solid #6d5fcc;
  border-radius:16px;padding:32px 36px;text-align:center;margin:20px 0;}
.thankyou-box h2{color:#a78bfa;font-size:2rem;margin:0 0 8px;}
.thankyou-box p{color:#c5c3e0;font-size:1rem;margin:6px 0;}
.share-action{background:#1e1e2e;border:1px solid #6d5fcc;border-radius:10px;padding:16px 20px;
  margin:10px 0;text-align:center;color:#c5c3e0;font-size:0.9rem;}
.dl-ready-box{background:#0d1f0d;border:2px solid #34d399;border-radius:12px;padding:20px 24px;margin:16px 0;}
@keyframes fadeIn{from{opacity:0;transform:translateY(6px);}to{opacity:1;transform:none;}}
</style>
""", unsafe_allow_html=True)

# ── Session state init ────────────────────────────────────────────────────────
for key in ["pdf_bytes","docx_bytes","md_bytes","report_generated",
            "user_info","pipeline_done","findings","kpis","narrative",
            "share_url","dataset_name","target_col","task_type",
            "max_f","ada_f","iris_f","rex_f","synth_f","leaderboard"]:
    if key not in st.session_state:
        st.session_state[key] = None

# ── Hero ─────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="hero">
  <h1>🧠 DataMind AI</h1>
  <p>A council of AI agents analyzes your data · generates 5 KPI stories · creates a PDF, Word & shareable report.</p>
</div>
""", unsafe_allow_html=True)

# ── Shared link handler ───────────────────────────────────────────────────────
shared_token = st.query_params.get("report", None)
if shared_token:
    from src.notifications import decode_share_token, send_notification_email
    meta = decode_share_token(shared_token)
    if meta:
        st.markdown(f"### 📄 Shared Report: {meta.get('dataset_name','Report')}")
        with st.form("shared_form"):
            st.markdown("**Please introduce yourself to view this report:**")
            c1, c2 = st.columns(2)
            with c1:
                vn = st.text_input("Your name *")
                ve = st.text_input("Your email *")
            with c2:
                vc = st.text_input("Company")
                vr = st.text_input("Your role")
            if st.form_submit_button("View report →", type="primary") and vn and ve:
                send_notification_email("view_link", meta.get("dataset_name",""), "Web link",
                    {"name":vn,"email":ve,"company":vc,"role":vr},
                    share_url=f"?report={shared_token}")
                st.success("Welcome! Here is the report:")
                st.markdown(f"**Generated:** {meta.get('generated_at','')}")
                st.markdown(f"**Best model:** {meta.get('best_model','')} — score {meta.get('best_score',0):.4f}")
                st.markdown("---")
                st.markdown(meta.get("narrative","Report preview unavailable. Upload the dataset to see the full analysis."))
                st.info("Upload the original dataset on the main page for the full interactive report with charts, KPIs, and downloads.")
    else:
        st.error("This report link is invalid or has expired.")
    st.stop()

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## ⚙️ Settings")
    uploaded = st.file_uploader("Upload dataset", type=["csv","xlsx","parquet"])
    groq_key = st.text_input("Groq API key (free)", type="password",
                              placeholder="gsk_...",
                              help="Free at console.groq.com — enables AI-written reports")
    app_url  = st.text_input("Your deployed app URL",
                              placeholder="https://datamind.streamlit.app",
                              help="Paste your Streamlit Cloud URL to make share links work")

    if uploaded:
        try:
            if uploaded.name.endswith(".csv"):         pv = pd.read_csv(uploaded, nrows=5)
            elif uploaded.name.endswith((".xlsx",".xls")): pv = pd.read_excel(uploaded, nrows=5)
            else:                                       pv = pd.read_parquet(uploaded)
            uploaded.seek(0)
            target_col = st.selectbox("Target column", list(pv.columns))
            task_type  = st.selectbox("Task type", ["auto","classification","regression"])
            run_btn    = st.button("🚀 Launch council", type="primary", use_container_width=True)
        except Exception as e:
            st.error(f"Error: {e}"); run_btn = False
    else:
        st.info("Upload a CSV to begin"); run_btn = False

    st.markdown("---")
    for em, nm, rl in [("🔬","Ada","EDA"),("⚡","Max","ML"),("💡","Iris","Insights"),
                        ("🔍","Rex","Critic"),("💻","Cleo","Code"),("🧠","Synthesis","Writer")]:
        st.markdown(f"{em} **{nm}** — {rl}")
    st.markdown("---")
    st.markdown("**[⭐ Star on GitHub](https://github.com/Rachana-Kotha/datamind-ai)**")

# ── Landing ───────────────────────────────────────────────────────────────────
if not uploaded:
    c1,c2,c3 = st.columns(3)
    with c1: st.markdown("### 📊 5 AI-selected KPIs\nAuto-selected with plain-English story for each")
    with c2: st.markdown("### 📄 PDF + Word export\nBranded reports ready to share with your team")
    with c3: st.markdown("### 🔗 Shareable web link\nEvery report gets a unique URL. Track who views it.")
    if st.button("Try demo (Iris dataset)"):
        from sklearn.datasets import load_iris
        load_iris(as_frame=True).frame.to_csv("/tmp/iris_demo.csv", index=False)
        st.success("Demo saved to /tmp/iris_demo.csv — upload it above!")
    st.stop()

# ── Load data ─────────────────────────────────────────────────────────────────
with st.expander("Dataset preview", expanded=False):
    st.dataframe(pv, use_container_width=True)

if not run_btn and not st.session_state.pipeline_done:
    st.info("Configure settings in the sidebar and click **Launch council**.")
    st.stop()

# ── Run pipeline ──────────────────────────────────────────────────────────────
if run_btn:
    # Reset state on new run
    for k in ["pdf_bytes","docx_bytes","md_bytes","report_generated","user_info"]:
        st.session_state[k] = None

    MAX_BYTES = 20 * 1024 * 1024
    if uploaded.size > MAX_BYTES:
        st.error(f"File too large. Maximum upload size is {MAX_BYTES // (1024 * 1024)} MB.")
        st.stop()

    suffix = os.path.splitext(uploaded.name)[1].lower()
    with tempfile.NamedTemporaryFile(prefix="datamind_", suffix=suffix, delete=False) as tf:
        tf.write(uploaded.getvalue())
        tmp = tf.name
    try:
        if suffix == ".csv":
            df = pd.read_csv(tmp)
        elif suffix in (".xlsx", ".xls"):
            df = pd.read_excel(tmp)
        else:
            df = pd.read_parquet(tmp)
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass

    tt = task_type
    if tt == "auto":
        tgt = df[target_col]
        tt = "classification" if (tgt.dtype == "object" or tgt.nunique() <= 20) else "regression"

    st.markdown("---")
    st.markdown("## 🤖 Council in session")
    agent_cont = st.container()

    def on_thought(name, emoji, msg):
        color = {"Ada":"#10b981","Max":"#3b82f6","Iris":"#f59e0b",
                 "Rex":"#ef4444","Cleo":"#8b5cf6","Synthesis":"#a78bfa"}.get(name,"#9d9db8")
        with agent_cont:
            st.markdown(f'<div class="agent-card"><div class="agent-name" style="color:{color}">{emoji} {name}</div><div class="agent-msg">{msg}</div></div>',
                        unsafe_allow_html=True)

    from agents.orchestrator import Orchestrator, AgentMemory
    from agents.council import EDAAgent, MLAgent, InsightAgent, CriticAgent, CodeAgent
    from agents.synthesis import SynthesisAgent
    from src.kpi_engine import select_top_kpis, generate_kpi_stories, generate_data_narrative

    memory = AgentMemory()
    orch   = Orchestrator(progress_callback=on_thought, memory=memory)
    for Cls in [EDAAgent, MLAgent, InsightAgent, CriticAgent, CodeAgent]:
        orch.register_agent(Cls(memory=memory, progress_callback=on_thought))
    orch.register_agent(SynthesisAgent(memory=memory, groq_api_key=groq_key or None,
                                       progress_callback=on_thought))

    with st.spinner("Council working..."):
        result   = orch.run(df, target_col, tt)
        findings = result["findings"]
        ada_f    = findings.get("Ada", {})
        max_f    = findings.get("Max", {})
        iris_f   = findings.get("Iris", {})
        rex_f    = findings.get("Rex", {})
        synth_f  = findings.get("Synthesis", {})

        on_thought("Synthesis","🧠","Selecting top 5 KPIs...")
        kpis = select_top_kpis(df, target_col, max_f.get("feature_importance"), n=5)
        kpis = generate_kpi_stories(kpis, uploaded.name, target_col, tt,
                                    groq_api_key=groq_key or None)

        on_thought("Synthesis","🧠","Writing the data narrative...")
        narrative = generate_data_narrative(kpis, max_f, ada_f, uploaded.name,
                                           target_col, tt, groq_api_key=groq_key or None)

    # Build share URL
    from src.notifications import build_share_url
    base = (app_url.strip().rstrip("/") if app_url.strip() else "http://localhost:8501")
    share_meta = {"dataset_name":uploaded.name,"target_col":target_col,
                  "task_type":tt,"narrative":narrative,
                  "best_model":max_f.get("best_model","N/A"),
                  "best_score":max_f.get("best_score",0),
                  "generated_at":datetime.now().isoformat()}
    share_url = build_share_url(base, share_meta)

    # Store everything in session_state
    st.session_state.update({
        "pipeline_done":True, "findings":findings,
        "kpis":kpis, "narrative":narrative, "share_url":share_url,
        "dataset_name":uploaded.name, "target_col":target_col, "task_type":tt,
        "max_f":max_f, "ada_f":ada_f, "iris_f":iris_f,
        "rex_f":rex_f, "synth_f":synth_f,
        "leaderboard":max_f.get("leaderboard",[]),
    })
    st.success(f"✅ Council complete in {result['elapsed_seconds']}s!")
    st.rerun()

# ── Guard: need pipeline done ─────────────────────────────────────────────────
if not st.session_state.pipeline_done:
    st.stop()

# ── Restore from session_state ────────────────────────────────────────────────
findings   = st.session_state.findings
kpis       = st.session_state.kpis
narrative  = st.session_state.narrative
share_url  = st.session_state.share_url
dname      = st.session_state.dataset_name
target_col = st.session_state.target_col
task_type  = st.session_state.task_type
max_f      = st.session_state.max_f
ada_f      = st.session_state.ada_f
iris_f     = st.session_state.iris_f
rex_f      = st.session_state.rex_f
synth_f    = st.session_state.synth_f
leaderboard= st.session_state.leaderboard or []
shape      = ada_f.get("shape", {})
insights   = iris_f.get("insights", [])
risks      = rex_f.get("risks", [])
debate     = synth_f.get("debate", [])

# ── Share link banner ─────────────────────────────────────────────────────────
st.markdown(f"""
<div class="share-box">
  <span style="color:#a78bfa;font-weight:700;font-size:1rem;">🔗 Your shareable report link</span><br>
  <span style="color:#c5c3e0;font-size:0.82rem;">Share with anyone — you get an email with their details when they view it.</span>
  <div style="background:#0d1117;border-radius:8px;padding:10px 14px;margin-top:10px;
       word-break:break-all;font-family:monospace;font-size:0.8rem;color:#e2e8f0;">{share_url}</div>
</div>
""", unsafe_allow_html=True)

# ── Tabs ──────────────────────────────────────────────────────────────────────
tab_kpi, tab_story, tab_models, tab_debate, tab_risks, tab_code, tab_export = st.tabs([
    "📊 KPIs","📖 Story","🏆 Models","🗣️ Debate","🔍 Risks","💻 Code","📥 Export & Download"
])

# ── KPI tab ───────────────────────────────────────────────────────────────────
with tab_kpi:
    st.markdown("### Top 5 KPIs — AI selected & narrated")
    cols = st.columns(2)
    for i, kpi in enumerate(kpis):
        col_name  = kpi.get("title", kpi.get("column","KPI"))
        mean_val  = kpi.get("mean", 0)
        trend     = kpi.get("trend_direction","flat")
        trend_pct = kpi.get("trend_pct", 0)
        corr      = kpi.get("target_correlation")
        story     = kpi.get("story","")

        if   abs(mean_val) >= 1_000_000: val_str = f"{mean_val/1_000_000:.2f}M"
        elif abs(mean_val) >= 1_000:     val_str = f"{mean_val/1_000:.2f}K"
        else:                             val_str = f"{mean_val:.3f}"

        ti   = "▲" if trend=="up" else "▼" if trend=="down" else "●"
        tc   = f"kpi-trend-{trend}"
        ch   = f"<span style='color:#9d9db8;font-size:0.78rem'>r={corr:.2f} vs target</span>" if corr else ""
        with cols[i % 2]:
            st.markdown(f"""<div class="kpi-card">
  <div class="kpi-lbl">KPI {i+1}</div>
  <div style="font-size:1rem;font-weight:700;color:#e8e6ff;margin:4px 0">{col_name}</div>
  <div class="kpi-val">{val_str}</div>
  <div style="display:flex;gap:12px;margin-top:6px;align-items:center">
    <span class="{tc}">{ti} {trend_pct:+.1f}%</span>{ch}
    <span style="color:#6b6b8a;font-size:0.78rem">n={kpi.get('count',0):,}</span>
  </div>
  <div class="kpi-story">{story}</div>
</div>""", unsafe_allow_html=True)

# ── Story tab ─────────────────────────────────────────────────────────────────
with tab_story:
    st.markdown("### Data intelligence narrative")
    st.markdown(narrative)

# ── Models tab ────────────────────────────────────────────────────────────────
with tab_models:
    c1,c2,c3,c4 = st.columns(4)
    for col, val, lbl in [
        (c1, f"{shape.get('rows',0):,}", "Rows"),
        (c2, str(shape.get("cols",0)), "Columns"),
        (c3, f"{max_f.get('best_score',0):.4f}", f"Best {max_f.get('metric_name','score')}"),
        (c4, str(max_f.get("best_model","N/A")), "Best model"),
    ]:
        with col:
            st.markdown(f'<div class="metric-box"><div class="metric-val">{val}</div><div class="metric-lbl">{lbl}</div></div>',
                        unsafe_allow_html=True)
    if leaderboard:
        st.dataframe(pd.DataFrame(leaderboard), use_container_width=True, hide_index=True)
    fi = max_f.get("feature_importance")
    if fi:
        st.markdown("#### Feature importances")
        st.bar_chart(pd.DataFrame({"Feature":fi["features"],"Importance":fi["importances"]}).set_index("Feature"), color="#7c3aed")

# ── Debate tab ────────────────────────────────────────────────────────────────
with tab_debate:
    for i, e in enumerate(debate):
        cls = "debate-left" if i%2==0 else "debate-right"
        st.markdown(f'<div class="debate-bubble {cls}"><strong>{e["emoji"]} {e["agent"]}</strong><br>{e["message"]}</div>',
                    unsafe_allow_html=True)

# ── Risks tab ─────────────────────────────────────────────────────────────────
with tab_risks:
    if not risks:
        st.success("No critical risks detected.")
    for r in risks:
        sev = r.get("severity","low")
        css = "risk-high" if sev in ["high","critical"] else "risk-medium" if sev=="medium" else "risk-high"
        st.markdown(f'<div class="{css}"><strong>[{sev.upper()}] {r.get("risk","")}</strong><br>{r.get("detail","")}</div>',
                    unsafe_allow_html=True)
    for ins in insights:
        st.markdown(f'<div class="insight-card">💡 <strong>{ins.get("title","")}</strong><br>{ins.get("detail","")}</div>',
                    unsafe_allow_html=True)

# ── Code tab ──────────────────────────────────────────────────────────────────
with tab_code:
    for nm, code in findings.get("Cleo",{}).get("snippets",{}).items():
        st.markdown(f"**{nm.replace('_',' ').title()}**")
        st.code(code, language="python")

# ── Export tab ────────────────────────────────────────────────────────────────
with tab_export:

    # ── SHOW THANK-YOU PAGE if report already generated ───────────────────────
    if st.session_state.report_generated:
        uinfo = st.session_state.user_info or {}

        st.markdown(f"""
<div class="thankyou-box">
  <div style="font-size:3rem">🎉</div>
  <h2>Thanks, {uinfo.get('name','').split()[0] if uinfo.get('name') else 'there'}!</h2>
  <p>Your reports are ready. Click the download buttons below.</p>
  <p style="color:#9d9db8;font-size:0.9rem;">We loved having you — please share this tool with others!</p>
</div>
""", unsafe_allow_html=True)

        # ── DOWNLOAD BUTTONS — always rendered, bytes from session_state ──────
        st.markdown('<div class="dl-ready-box">', unsafe_allow_html=True)
        st.markdown("### ⬇️ Your reports are ready")
        dl1, dl2, dl3 = st.columns(3)

        if st.session_state.pdf_bytes:
            with dl1:
                st.download_button(
                    label="📄 Download PDF",
                    data=st.session_state.pdf_bytes,
                    file_name=f"DataMind_{dname.split('.')[0]}.pdf",
                    mime="application/pdf",
                    use_container_width=True,
                    type="primary",
                )

        if st.session_state.docx_bytes:
            with dl2:
                st.download_button(
                    label="📝 Download Word",
                    data=st.session_state.docx_bytes,
                    file_name=f"DataMind_{dname.split('.')[0]}.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    use_container_width=True,
                )

        if st.session_state.md_bytes:
            with dl3:
                st.download_button(
                    label="📋 Download Markdown",
                    data=st.session_state.md_bytes,
                    file_name=f"DataMind_{dname.split('.')[0]}.md",
                    mime="text/markdown",
                    use_container_width=True,
                )
        st.markdown("</div>", unsafe_allow_html=True)

        # ── SHARE ACTIONS ────────────────────────────────────────────────────
        st.markdown("---")
        st.markdown("### 🌍 Spread the word")
        st.caption("Help other data scientists discover this free tool:")

        li_text = f"Just analyzed my dataset with DataMind AI — a free open-source tool where 5 AI agents debate your data and generate a branded intelligence report. Check it out! #DataScience #AI #OpenSource {share_url}"
        tw_text = f"I just used DataMind AI to analyze my data — 5 AI agents debated my dataset and wrote me a full PDF report. 100% free. Try it here: {share_url} #DataScience #AI"

        sh1, sh2, sh3 = st.columns(3)
        with sh1:
            st.markdown(f"""<div class="share-action">
              <div style="font-size:1.5rem">💼</div>
              <div style="font-weight:700;color:#0a66c2;margin:6px 0">Share on LinkedIn</div>
              <div style="font-size:0.8rem;color:#9d9db8">Paste the text below into a LinkedIn post</div>
            </div>""", unsafe_allow_html=True)
            st.code(li_text, language=None)

        with sh2:
            st.markdown(f"""<div class="share-action">
              <div style="font-size:1.5rem">🐦</div>
              <div style="font-weight:700;color:#1da1f2;margin:6px 0">Share on X / Twitter</div>
              <div style="font-size:0.8rem;color:#9d9db8">Ready-to-paste tweet</div>
            </div>""", unsafe_allow_html=True)
            st.code(tw_text, language=None)

        with sh3:
            st.markdown(f"""<div class="share-action">
              <div style="font-size:1.5rem">🔗</div>
              <div style="font-weight:700;color:#a78bfa;margin:6px 0">Your report link</div>
              <div style="font-size:0.8rem;color:#9d9db8">Anyone with this can view your report</div>
            </div>""", unsafe_allow_html=True)
            st.code(share_url, language=None)

        # ── EXPERIENCE FEEDBACK ───────────────────────────────────────────────
        st.markdown("---")
        st.markdown("### 💬 Share your experience")
        st.caption("What did you discover? Your feedback helps us improve DataMind AI.")

        with st.form("feedback_form"):
            rating = st.select_slider("How useful was this report?",
                                      options=["⭐","⭐⭐","⭐⭐⭐","⭐⭐⭐⭐","⭐⭐⭐⭐⭐"],
                                      value="⭐⭐⭐⭐⭐")
            experience = st.text_area(
                "What was the most valuable insight you got?",
                placeholder="The agents caught a data leakage issue I had missed...",
                height=100,
            )
            fb_btn = st.form_submit_button("Submit feedback", type="primary")
            if fb_btn:
                from src.notifications import send_notification_email
                send_notification_email(
                    event_type="feedback",
                    dataset_name=dname,
                    format_name="Feedback",
                    user_info=uinfo,
                    extra_notes=f"Rating: {rating}\nExperience: {experience}",
                )
                st.success("Thank you! Your feedback means a lot. 🙏")
                st.balloons()

        # option to generate a different format
        st.markdown("---")
        if st.button("⬅️ Generate a different format"):
            st.session_state.report_generated = False
            st.rerun()

    else:
        # ── FORM — collect user info & select formats ──────────────────────────
        st.markdown("### 📥 Generate & download your report")
        st.markdown("Enter your details to personalise the report and help us understand our users.")

        with st.form("export_form"):
            c1, c2 = st.columns(2)
            with c1:
                u_name    = st.text_input("Your name *", placeholder="Jane Smith")
                u_email   = st.text_input("Your email *", placeholder="jane@company.com")
            with c2:
                u_company = st.text_input("Company / organisation", placeholder="Acme Corp")
                u_role    = st.text_input("Your role", placeholder="Data Scientist")

            st.markdown("**Select formats to generate:**")
            fc1, fc2, fc3 = st.columns(3)
            with fc1: want_pdf  = st.checkbox("📄 PDF (recommended)", value=True)
            with fc2: want_docx = st.checkbox("📝 Word (.docx)")
            with fc3: want_md   = st.checkbox("📋 Markdown (.md)")

            gen_btn = st.form_submit_button("✨ Generate my report", type="primary",
                                            use_container_width=True)

        if gen_btn:
            if not u_name.strip() or not u_email.strip():
                st.error("Please enter your name and email to continue.")
                st.stop()

            report_args = dict(
                dataset_name=dname, target_col=target_col, task_type=task_type,
                narrative=narrative, kpis=kpis, ml_findings=max_f, eda_findings=ada_f,
                insights=insights, risks=risks, debate=debate, share_url=share_url,
            )

            with st.spinner("Building your branded reports — this takes about 10 seconds..."):
                # Generate all selected formats and store bytes in session_state
                if want_pdf:
                    from src.pdf_report import generate_pdf
                    st.session_state.pdf_bytes = generate_pdf(**report_args)

                if want_docx:
                    from src.docx_report import generate_docx
                    st.session_state.docx_bytes = generate_docx(**report_args)

                if want_md:
                    md = f"# DataMind AI — {dname}\n\n{narrative}\n\n---\n\n## Top 5 KPIs\n\n"
                    for kpi in kpis:
                        md += f"### {kpi.get('title', kpi.get('column',''))}\n{kpi.get('story','')}\n\n"
                    md += f"---\n\n## Best model\n{max_f.get('best_model','')} — {max_f.get('metric_name','score')}: {max_f.get('best_score',0):.4f}\n\n"
                    md += f"## Share link\n{share_url}\n"
                    st.session_state.md_bytes = md.encode("utf-8")

                # Store user info & send email
                uinfo = {"name":u_name,"email":u_email,"company":u_company,"role":u_role}
                st.session_state.user_info = uinfo
                st.session_state.report_generated = True

                fmts = ", ".join(f for f, c in [("PDF",want_pdf),("Word",want_docx),("Markdown",want_md)] if c)
                from src.notifications import send_notification_email
                send_notification_email(
                    event_type="download",
                    dataset_name=dname,
                    format_name=fmts,
                    user_info=uinfo,
                    share_url=share_url,
                )

            st.rerun()  # rerun → session_state.report_generated=True → shows thank-you page with download buttons
